### ISSUE TITLE
Adopt mandatory order

### ISSUE THREAD

**Issue by dikti** [apple/password-manager-resources#15]
While the files currently are relatively short, they will probably fill up with rules in no time. To maintain some sort of clarity, I propose to add a mandatory order, like alphabetical, to the contribution rules.

**Comment by ejdyksen** [comment]
Actually, as the lists get longer, keeping them alphabetical will reduce the chance of merge conflicts.

If all additions append to the end of the list, they will all be in conflict with each other basically 100% of the time.

**Comment by rmondello** [comment]
We should automate our way out of this problem. For now, to continue bootstrapping, I’ll clarify the README, re-sort the files, and help people with their merges. :)

**Comment by julian-klode** [comment]
You probably want one file per site, really, as otherwise git will scale terribly if you all edit the same file all the time. We see that in other repos that keep a log file of sorts, git just becomes unusably slow.

This also has the advantage that you can edit/add sites in parallel that are similar in name. Currently, if you were to add 3 pull requests for sites starting with signin, one would merge fine and the other will have conflicts.

**Comment by igor-makarov** [comment]
Ultimately, it's nothing that the individual PR contributors cannot resolve with some rebasing.
