### ISSUE TITLE
Add a rule for identitytheft.gov

### ISSUE THREAD

**Issue by rmondello** [apple/password-manager-resources#314]
Add a rule for identitytheft.gov

<img width="661" alt="Screen Shot 2020-08-10 at 4 38 51 PM" src="https://user-images.githubusercontent.com/234616/90675327-27e61b80-e20f-11ea-8c68-b34af801e0eb.png">

**Comment by hisaac** [comment]
I have a PR ready, but in order to test it, are you able to provide a link or steps to get to a place where you can create a password? I'm clicking around identitytheft.gov, but I can't see a "create account" option anywhere.

**Comment by rmondello** [comment]
@hisaac This one’s tricky. I think you should submit the PR, and in the request, provide 10 passwords generated with your rules from the [developer tool](https://developer.apple.com/password-rules/). I’ll then work on getting them tested.

How does that sound?

**Comment by hisaac** [comment]
Works for me! I'll submit the PR shortly.

**Comment by hisaac** [comment]
I may have found an issue with the developer tool. (Or more likely, I'm just using it wrong.)

I used this as the seed in the top text box:

```
allowed: upper;
allowed: lower;
allowed: digit;
allowed: [!#%&*@^];
```

Which outputs this as the quirk:

```
allowed: upper,lower,digit,[!#%&*@^];
```

The problem is, the generator doesn't actually include any of the special characters:

```
taswyGpisme8mutjys
ripqaxTemfagmeqwu7
syjdyxwosmo0Wecvug
```

I'd have assumed that since those special characters were allowed, at least one would be included in the generated passwords.

I noticed that when I used `required` instead of `allowed` like so:

```
required: upper;
required: lower;
required: digit;
required: [!#%&*@^];
```

It generates a separate `required` statement for each one in the quirk, rather than combining them.

```
required: upper; required: lower; required: digit; required: [!#%&*@^];
```

And the generated passwords seem to more closely match the rule:

```
!^8^XYg8U8sI
mybXJG*R1t*h
5GRVrY1*RV5k
```

Am I using the tool wrong perhaps? Or is it not correctly generating a quirk from my input?

**Comment by rmondello** [comment]
> I'd have assumed that since those special characters were allowed, at least one would be included in the generated passwords.

Right now, the tool tries to mirror what Safari would do with those rules, not what a generate generator would do. Since those special characters are allowed, but not required, and Safari prefers to generate passwords without special characters (other than `-`), you’re not seeing passwords with those characters.

Your rule looks fine!

**Comment by hisaac** [comment]
Ah ok, that makes sense. I'll submit a PR ASAP then.
